### PR TITLE
MNT: rerender

### LINKED ISSUE #2: @conda-forge-admin, please rerender
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #2.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes #2

### CODE REVIEW

**Comment by bgruening** [comment]
> r-mass -> r-base[version='>=3.4.1,<3.4.2.0a0,>=3.4.2,<3.4.3a0,>=3.5.0,<3.5.1.0a0']


But r-mass has 3.6 builds afaik....

**Comment by dpryan79** [comment]
CDN issue?

**Comment by bgruening** [comment]
I can see it with conda search.

**Comment by cbrueffer** [comment]
@conda-forge-admin please rerender

**Comment by dbast** [comment]
Something seems to be seriously broken:
```
Package r-base conflicts for:
r-ggplot2 -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-r6 -> r-base[version='3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-viridis -> r-ggplot2[version='>=1.0.1'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-r6 -> r-base[version='3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-lavaan -> r-pbivnorm -> r-base[version='3.3.2.*,3.4.1.*,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-gparotation -> r-base[version='3.3.2.*,3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-gridextra -> r-gtable -> r-base[version='3.2.2.*,3.3.2.*,>=3.4.3,<3.4.4.0a0,>=3.5.0,<3.5.1.0a0,>=3.5.1,<3.5.2.0a0']
r-xtable -> r-base[version='3.2.1.*,3.2.2.*,3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.4.2,<3.4.3a0']
r-plyr -> r-rcpp[version='>=0.11.0'] -> r-base[version='3.2.2.*,3.4.1.*,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-xml -> r-base[version='3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5.0,<3.5.1.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-pander -> r-rcpp -> r-base[version='3.4.1.*,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-base=3.6
r-diagrammer -> r-viridis[version='>=0.5.0'] -> r-ggplot2[version='>=1.0.1'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-r6 -> r-base[version='3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-psych -> r-mnormt -> r-base[version='3.2.1.*,3.4.1.*,>=3.4.3,<3.4.4.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0']
r-ggrepel -> r-scales[version='>=0.3.0'] -> r-r6 -> r-base[version='3.4.1.*,>=3.5.1,<3.5.2.0a0']
r-rcolorbrewer -> r-base[version='3.2.1.*,3.2.2.*,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-mass -> r-base[version='3.2.0.*,3.2.1.*,3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-rio -> r-haven[version='>=1.1.0'] -> r-readr[version='>=0.1.0'] -> r-r6 -> r-base[version='3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-ggally -> r-ggplot2[version='>2.2.0,>=2.2.0'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-r6 -> r-base[version='3.4.1.*,>=3.5.1,<3.5.2.0a0']
r-scrt -> r-base[version='3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-mbess -> r-lavaan -> r-pbivnorm -> r-base[version='3.4.1.*,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0']
r-gtable -> r-base[version='3.2.2.*,3.3.2.*,>=3.4.3,<3.4.4.0a0,>=3.5.0,<3.5.1.0a0,>=3.5.1,<3.5.2.0a0']
r-ufs[version='>=0.0.1'] -> r-viridis[version='>=0.5.1'] -> r-ggplot2[version='>=1.0.1'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-r6 -> r-base[version='3.4.1.*,>=3.5.1,<3.5.2.0a0']
r-diptest -> r-base[version='3.3.2.*,3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-biasedurn -> r-base[version='3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-lme4 -> r-rcppeigen -> r-matrix[version='>=1.1_0'] -> r-lattice -> r-base[version='3.1.3.*,3.2.2.*,3.3.2.*,>=3.5.0,<3.5.1.0a0,>=3.5.1,<3.5.2.0a0']
r-minpack.lm -> r-base[version='3.3.2.*,3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-scales -> r-r6 -> r-base[version='3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-car -> r-rio -> r-haven[version='>=1.1.0'] -> r-readr[version='>=0.1.0'] -> r-r6 -> r-base[version='3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-knitr -> r-markdown -> r-mime[version='>=0.3'] -> r-base[version='3.2.2.*,>=3.4.1,<3.4.2.0a0,>=3.4.3,<3.4.4.0a0,>=3.5.0,<3.5.1.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-digest -> r-base[version='3.3.2.*,3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.4.3,<3.4.4.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-ggridges -> r-scales[version='>=0.4.1'] -> r-r6 -> r-base[version='3.4.1.*,>=3.5.1,<3.5.2.0a0']
r-data.tree -> r-diagrammer[version='>=1.0.0'] -> r-viridis[version='>=0.5.0'] -> r-ggplot2[version='>=1.0.1'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-r6 -> r-base[version='3.4.1.*,>=3.5.1,<3.5.2.0a0']
r-suppdists -> r-base[version='3.3.2.*,3.4.1.*,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-pwr -> r-base[version='3.3.2.*,3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
```

Filtering all the lines, that do not contain 3.6, leaves:
```
r-ggplot2 -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-r6 -> r-base[version='3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-viridis -> r-ggplot2[version='>=1.0.1'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-r6 -> r-base[version='3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-gridextra -> r-gtable -> r-base[version='3.2.2.*,3.3.2.*,>=3.4.3,<3.4.4.0a0,>=3.5.0,<3.5.1.0a0,>=3.5.1,<3.5.2.0a0']
r-xtable -> r-base[version='3.2.1.*,3.2.2.*,3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.4.2,<3.4.3a0']
r-diagrammer -> r-viridis[version='>=0.5.0'] -> r-ggplot2[version='>=1.0.1'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-r6 -> r-base[version='3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-ggrepel -> r-scales[version='>=0.3.0'] -> r-r6 -> r-base[version='3.4.1.*,>=3.5.1,<3.5.2.0a0']
r-rio -> r-haven[version='>=1.1.0'] -> r-readr[version='>=0.1.0'] -> r-r6 -> r-base[version='3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-ggally -> r-ggplot2[version='>2.2.0,>=2.2.0'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-r6 -> r-base[version='3.4.1.*,>=3.5.1,<3.5.2.0a0']
r-gtable -> r-base[version='3.2.2.*,3.3.2.*,>=3.4.3,<3.4.4.0a0,>=3.5.0,<3.5.1.0a0,>=3.5.1,<3.5.2.0a0']
r-ufs[version='>=0.0.1'] -> r-viridis[version='>=0.5.1'] -> r-ggplot2[version='>=1.0.1'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-r6 -> r-base[version='3.4.1.*,>=3.5.1,<3.5.2.0a0']
r-lme4 -> r-rcppeigen -> r-matrix[version='>=1.1_0'] -> r-lattice -> r-base[version='3.1.3.*,3.2.2.*,3.3.2.*,>=3.5.0,<3.5.1.0a0,>=3.5.1,<3.5.2.0a0']
r-scales -> r-r6 -> r-base[version='3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-car -> r-rio -> r-haven[version='>=1.1.0'] -> r-readr[version='>=0.1.0'] -> r-r6 -> r-base[version='3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-ggridges -> r-scales[version='>=0.4.1'] -> r-r6 -> r-base[version='3.4.1.*,>=3.5.1,<3.5.2.0a0']
r-data.tree -> r-diagrammer[version='>=1.0.0'] -> r-viridis[version='>=0.5.0'] -> r-ggplot2[version='>=1.0.1'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-r6 -> r-base[version='3.4.1.*,>=3.5.1,<3.5.2.0a0']
```

Cutting the tree and removing duplicates, leaves:
```
r-r6 -> r-base[version='3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-gtable -> r-base[version='3.2.2.*,3.3.2.*,>=3.4.3,<3.4.4.0a0,>=3.5.0,<3.5.1.0a0,>=3.5.1,<3.5.2.0a0']
r-xtable -> r-base[version='3.2.1.*,3.2.2.*,3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.4.2,<3.4.3a0']
r-lattice -> r-base[version='3.1.3.*,3.2.2.*,3.3.2.*,>=3.5.0,<3.5.1.0a0,>=3.5.1,<3.5.2.0a0']
```

**Comment by dbast** [comment]
Uh. This was automatically closed. Will reopen in some minutes.

**Comment by dbast** [comment]
Now:
```
r-gtable -> r-base[version='3.2.2.*,3.3.2.*,>=3.4.2,<3.4.3a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-suppdists -> r-base[version='3.3.2.*,3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-xtable -> r-base[version='3.3.2.*,>=3.4.2,<3.4.3a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0']
r-ggplot2 -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-rcolorbrewer -> r-base[version='3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.0,<3.5.1.0a0']
r-scrt -> r-base[version='3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-mass -> r-base[version='3.2.2.*,3.3.2.*,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-digest -> r-base[version='3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.4.3,<3.4.4.0a0,>=3.5.1,<3.5.2.0a0']
r-data.tree -> r-diagrammer[version='>=1.0.0'] -> r-rgexf[version='>=0.15.3'] -> r-igraph -> r-nmf -> r-ggplot2 -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-rcolorbrewer -> r-base[version='3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.0,<3.5.1.0a0']
r-xml -> r-base[version='3.2.0.*,3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.0,<3.5.1.0a0,>=3.5.1,<3.5.2.0a0']
r-diptest -> r-base[version='3.3.2.*,3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-ggally -> r-ggplot2[version='>2.2.0,>=2.2.0'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-rcolorbrewer -> r-base[version='3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.0,<3.5.1.0a0']
r-knitr -> r-highr -> r-base[version='3.1.3.*,3.2.1.*,3.2.2.*,>=3.5.1,<3.5.2.0a0']
r-ggrepel -> r-ggplot2[version='>=2.0.0,>=2.2.0'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-rcolorbrewer -> r-base[version='3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.0,<3.5.1.0a0']
r-psych -> r-foreign -> r-base[version='3.2.1.*,3.2.2.*,>=3.4.1,<3.4.2.0a0,>=3.6,<3.7.0a0']
r-minpack.lm -> r-base[version='3.3.2.*,3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-plyr -> r-rcpp[version='>=0.11.0'] -> r-base[version='3.2.0.*,3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.4.3,<3.4.4.0a0,>=3.5.1,<3.5.2.0a0']
r-biasedurn -> r-base[version='3.3.2.*,3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-rio -> r-readxl[version='>=0.1.1'] -> r-cellranger -> r-rematch -> r-base[version='>=3.4.1,<3.4.2.0a0,>=3.4.2,<3.4.3a0,>=3.4.3,<3.4.4.0a0,>=3.5.0,<3.5.1.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-lavaan -> r-numderiv -> r-base[version='3.2.1.*,3.2.2.*,3.3.2.*,3.4.1.*,>=3.5.0,<3.5.1.0a0']
r-car -> r-maptools -> r-sp[version='>=1.0_11'] -> r-lattice -> r-base[version='3.2.0.*,3.2.2.*,>=3.4.3,<3.4.4.0a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-diagrammer -> r-rgexf[version='>=0.15.3'] -> r-igraph -> r-nmf -> r-ggplot2 -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-rcolorbrewer -> r-base[version='3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.0,<3.5.1.0a0']
r-lme4 -> r-nloptr[version='>=1.0.4'] -> r-base[version='3.2.0.*,3.2.1.*,3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-scales -> r-rcolorbrewer -> r-base[version='3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.0,<3.5.1.0a0']
r-viridis -> r-ggplot2[version='>=1.0.1'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-rcolorbrewer -> r-base[version='3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.0,<3.5.1.0a0']
r-pwr -> r-base[version='3.3.2.*,3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-base=3.6
r-rcolorbrewer -> r-base[version='3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.0,<3.5.1.0a0']
r-mbess -> r-lavaan -> r-numderiv -> r-base=3.4.1
r-gparotation -> r-base[version='3.3.2.*,3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-gridextra -> r-gtable -> r-base[version='3.2.2.*,3.3.2.*,>=3.4.2,<3.4.3a0,>=3.5,<3.6.0a0,>=3.5.1,<3.5.2.0a0,>=3.6,<3.7.0a0']
r-ufs[version='>=0.0.1'] -> r-viridis[version='>=0.5.1'] -> r-ggplot2[version='>=1.0.1'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-rcolorbrewer -> r-base[version='>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.0,<3.5.1.0a0']
r-ggridges -> r-ggplot2[version='>=2.2.0'] -> r-scales[version='>=0.2.3,>=0.4.1,>=0.5.0'] -> r-rcolorbrewer -> r-base[version='3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.5,<3.6.0a0,>=3.5.0,<3.5.1.0a0']
r-pander -> r-rcpp -> r-base[version='3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5.1,<3.5.2.0a0']
```

Lines without 3.6:
```
r-digest -> r-base[version='3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.4.3,<3.4.4.0a0,>=3.5.1,<3.5.2.0a0']
r-xml -> r-base[version='3.2.0.*,3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.0,<3.5.1.0a0,>=3.5.1,<3.5.2.0a0']
r-knitr -> r-highr -> r-base[version='3.1.3.*,3.2.1.*,3.2.2.*,>=3.5.1,<3.5.2.0a0']
r-plyr -> r-rcpp[version='>=0.11.0'] -> r-base[version='3.2.0.*,3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.4.3,<3.4.4.0a0,>=3.5.1,<3.5.2.0a0']
r-lavaan -> r-numderiv -> r-base[version='3.2.1.*,3.2.2.*,3.3.2.*,3.4.1.*,>=3.5.0,<3.5.1.0a0']
r-lme4 -> r-nloptr[version='>=1.0.4'] -> r-base[version='3.2.0.*,3.2.1.*,3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-mbess -> r-lavaan -> r-numderiv -> r-base=3.4.1
r-pander -> r-rcpp -> r-base[version='3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5.1,<3.5.2.0a0']
```

Cutting the tree and removing duplicates, leaves:
```
r-digest -> r-base[version='3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.4.3,<3.4.4.0a0,>=3.5.1,<3.5.2.0a0']
r-xml -> r-base[version='3.2.0.*,3.2.1.*,3.4.1.*,>=3.4.2,<3.4.3a0,>=3.5.0,<3.5.1.0a0,>=3.5.1,<3.5.2.0a0']
r-highr -> r-base[version='3.1.3.*,3.2.1.*,3.2.2.*,>=3.5.1,<3.5.2.0a0']
r-numderiv -> r-base[version='3.2.1.*,3.2.2.*,3.3.2.*,3.4.1.*,>=3.5.0,<3.5.1.0a0']
r-nloptr[version='>=1.0.4'] -> r-base[version='3.2.0.*,3.2.1.*,3.3.2.*,>=3.4.1,<3.4.2.0a0,>=3.4.2,<3.4.3a0,>=3.5.1,<3.5.2.0a0']
r-rcpp -> r-base[version='3.4.1.*,>=3.4.1,<3.4.2.0a0,>=3.5.1,<3.5.2.0a0']
```

So the bump build number series had some effect. But what is happening here?

**Comment by dpryan79** [comment]
It looks like there's a bad package cache somewhere. There's definitely an r-xml build for R 3.6 (the same is likely true for the others).

**Comment by dbast** [comment]
@conda-forge-admin please rerender

**Comment by dbast** [comment]
solved via https://github.com/conda-forge/r-userfriendlyscience-feedstock/pull/1

**Pull request closed without merging**
